@WarehouseHub.Api_HostAddress = http://localhost:5242

GET {{WarehouseHub.Api_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{WarehouseHub.Api_HostAddress}}/api/auth/register

###
