<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WarehouseHub.Domain\WarehouseHub.Domain.csproj" />
    <ProjectReference Include="..\WarehouseHub.Contracts\WarehouseHub.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Users\" />
    <Folder Include="Products\" />
    <Folder Include="Common\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.11" />
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />
  </ItemGroup>

</Project>
